fix: `npm run build:dev` got `packages/react-babylonjs/src/plugins.ts(24,28): semantic error TS2343: This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.`